version: '3.1'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8181:8080
    networks:
      database-net:
  database:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Nzonkem@237
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: prod_db
    volumes:
      - database-data:/var/lib/mysql:rw
    networks:
      database-net:
volumes:
  database-data:
    driver: local
networks:
  database-net:
    driver: bridge
